# 同步仓库变量
name: synchronize variables
'on':
  # 手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'synchronize variables'
jobs:
  job1:
    name: 配置synchronize variables
    runs-on: ubuntu-latest
