name: bark notice

on: workflow_call

jobs:
  job1:
    name: bark notice
    runs-on: ubuntu-latest
    steps:
      - name: Push notification
        uses: shink/bark-action@v2
        continue-on-error: true
        with:
          key: ${{ secrets.BARK_KEY }} # Your secret key, it is required
          host: ${{ vars.BARK_HOST }} # Your Bark host, the default is 'https://api.day.app'
          title: Test Result
          body: Pass the qx and clash config generate test!
          sound: healthnotification
          isArchive: 1
          # url: https://yuanhaoji.com
          # automaticallyCopy: 1
          # copy: Content copied to clipboard
